################################
# 2048 Game - Imagen modificada
################################

# Namespace
apiVersion: v1
kind: Namespace
metadata: {
   name: "game"
   }

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: game
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        # Imagen modificada en repositorio personal de Docker Hub
        image: docker.io/pafdca/2048:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1

---
# Service
apiVersion: v1
kind: Service
metadata:
    name: game-service
    namespace: game
spec:
    selector:
      app: game
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game
  namespace: game
  labels:
    app: game
spec:
  rules:
  - host: game.bar
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: game-service
            port:
              number: 80

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: game
data:
  servers-increment: "42"
  ssl-redirect: "OFF"
