---

# Instalaci贸n de paquetes para probar las aplicaciones desde el controller

- name: instalaci贸n de xorg-x11-xauth.x86_64 para la exportaci贸n del display
  dnf:
    name: "xorg-x11-xauth.x86_64"
    state: present
  become: yes

- name: instalaci贸n de firefox para probar las aplicaciones desplegadas
  dnf:
    name: "firefox"
    state: present
  become: yes
